'\" t
.\"     Title: gnome-shell
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: December 2020
.\"    Manual: User Commands
.\"    Source: GNOME-SHELL
.\"  Language: English
.\"
.TH "GNOME\-SHELL" "1" "December 2020" "GNOME\-SHELL" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gnome-shell \- Graphical shell for the GNOME desktop
.SH "SYNOPSIS"
.sp
\fBgnome\-shell\fR [\fIOPTION\fR\&...]
.SH "DESCRIPTION"
.sp
GNOME shell provides core user interface functions for the GNOME 3 desktop, like switching to windows and launching applications\&. GNOME shell takes advantage of the capabilities of modern graphics hardware and introduces innovative user interface concepts to provide a visually attractive and easy to use experience\&.
.sp
gnome\-shell is a required component of the GNOME desktop, i\&.e\&. it is listed in the RequiredComponents field of /usr/share/gnome\-session/sessions/gnome\&.session\&. It is started in the window manager phase of the session\&.
.SH "OPTIONS"
.PP
\fB\-\-wayland\fR
.RS 4
Run as a wayland compositor
.RE
.PP
\fB\-\-display\-server\fR
.RS 4
Run as a full display server, rather than nested
.RE
.PP
\fB\-\-nested\fR
.RS 4
Run as a nested compositor
.RE
.PP
\fB\-\-no\-x11\fR
.RS 4
Run wayland compositor without starting Xwayland
.RE
.PP
\fB\-\-x11\fR
.RS 4
Run with X11 backend
.RE
.PP
\fB\-\-wayland\-display\fR=\fIDISPLAY\fR
.RS 4
Wayland display name to use
.RE
.PP
\fB\-d\fR, \fB\-\-display\fR=\fIDISPLAY\fR
.RS 4
X display to use
.RE
.PP
\fB\-r\fR, \fB\-\-replace\fR
.RS 4
Replace the running window manager
.RE
.PP
\fB\-\-sm\-disable\fR
.RS 4
Disable connection to the session manager
.RE
.PP
\fB\-\-sm\-client\-id\fR=\fIID\fR
.RS 4
Specify session management
\fIID\fR
.RE
.PP
\fB\-\-sm\-save\-file\fR=\fIFILE\fR
.RS 4
Initialize session from
\fIFILE\fR
.RE
.PP
\fB\-\-sync\fR
.RS 4
Make X calls synchronous
.RE
.PP
\fB\-\-mode\fR=\fIMODE\fR
.RS 4
Use a specific mode, e\&.g\&. "gdm" for login screen
.RE
.PP
\fB\-\-list\-modes\fR
.RS 4
List possible modes and exit
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version and exit
.RE
.PP
\fB\-\-help\fR
.RS 4
Display help and exit
.RE
.SH "FILES"
.sp
/usr/share/gnome\-session/sessions/gnome\&.session, /usr/share/applications/org\&.gnome\&.Shell\&.desktop\&.
.SH "BUGS"
.sp
The bug tracker can be reached by visiting the website \m[blue]\fBhttps://gitlab\&.gnome\&.org/GNOME/gnome\-shell/issues\fR\m[]\&. Before sending a bug report, please verify that you have the latest version of gnome\-shell\&. Many bugs (major and minor) are fixed at each release, and if yours is out of date, the problem may already have been solved\&.
.SH "ADDITIONAL INFORMATION"
.sp
For further information, visit the website \m[blue]\fBhttps://wiki\&.gnome\&.org/Projects/GnomeShell\fR\m[]\&.
