debian/source_gnome-shell.py /usr/share/apport/package-hooks
usr/share/GConf
usr/share/glib-2.0
usr/share/gnome-control-center
usr/share/gnome-shell
#usr/share/gtk-doc
usr/share/locale
debian/ubuntu-session-mods/ubuntu.json usr/share/gnome-shell/modes/
debian/ubuntu-session-mods/ubuntu.css usr/share/gnome-shell/theme/
# install upstream theme for gdm if vanilla gnome theme is selected
obj-*/data/theme/gnome-shell.css usr/share/gnome-shell/theme/
